In [1]:
import tensorflow as tf
import numpy as np
import pickle

In [2]:
with open("./data/janken-data.pkl", "rb") as fp:
    data = pickle.load(fp)

(x_train, y_train), (x_test, y_test) = data

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(30, activation='relu', input_dim=2),
    tf.keras.layers.Dense(3, activation='softmax')
])
model.compile(
    optimizer='adam',
    loss="sparse_categorical_crossentropy",
    metrics=['accuracy']
)

In [4]:
model.fit(x_train, y_train, epochs=20)
model.evaluate(x_test, y_test, verbose=2)

Epoch 1/20
63/63 [==============================] - 0s 2ms/step - loss: 1.1463 - accuracy: 0.1742
Epoch 2/20
63/63 [==============================] - 0s 2ms/step - loss: 1.0459 - accuracy: 0.3968
Epoch 3/20
63/63 [==============================] - 0s 2ms/step - loss: 0.9958 - accuracy: 0.6668
Epoch 4/20
63/63 [==============================] - 0s 2ms/step - loss: 0.9393 - accuracy: 0.9494
Epoch 5/20
63/63 [==============================] - 0s 2ms/step - loss: 0.8901 - accuracy: 0.9166
Epoch 6/20
63/63 [==============================] - 0s 2ms/step - loss: 0.8371 - accuracy: 1.0000
Epoch 7/20
63/63 [==============================] - 0s 2ms/step - loss: 0.7775 - accuracy: 1.0000
Epoch 8/20
63/63 [==============================] - 0s 2ms/step - loss: 0.7274 - accuracy: 1.0000
Epoch 9/20
63/63 [==============================] - 0s 2ms/step - loss: 0.6687 - accuracy: 1.0000
Epoch 10/20
63/63 [==============================] - 0s 2ms/step - loss: 0.6137 - accuracy: 1.0000
Epoch 11/20
63/63 [

[0.23352685570716858, 1.0]

In [5]:
def janken(a,b):
    hands = {'グー':0, 'チョキ':1, 'パー':2}
    results = ['あいこ', '負け', '勝ち']
    x = np.array([[hands[a], hands[b]]])
    r = model.predict(x)
    print(r)
    print(a, b, '→', results[r[0].argmax()])

In [6]:
janken('グー', 'グー')
janken('チョキ', 'パー')
janken('パー', 'チョキ')

[[0.92568105 0.03870279 0.03561612]]
グー グー → あいこ
[[0.11469261 0.19224985 0.69305754]]
チョキ パー → 勝ち
[[0.09263073 0.75071746 0.15665178]]
パー チョキ → 負け
